// Code generated by MockGen. DO NOT EDIT.
// Source: precheck.go
//
// Generated by this command:
//
//	mockgen -destination mock_precheck/mock_precheck.go -package mock_precheck -source precheck.go -typed
//

// Package mock_precheck is a generated GoMock package.
package mock_precheck

import (
	reflect "reflect"

	rbft "github.com/axiomesh/axiom-bft"
	common "github.com/axiomesh/axiom-ledger/internal/consensus/common"
	gomock "go.uber.org/mock/gomock"
)

// MockPreCheck is a mock of PreCheck interface.
type MockPreCheck struct {
	ctrl     *gomock.Controller
	recorder *MockPreCheckMockRecorder
}

// MockPreCheckMockRecorder is the mock recorder for MockPreCheck.
type MockPreCheckMockRecorder struct {
	mock *MockPreCheck
}

// NewMockPreCheck creates a new mock instance.
func NewMockPreCheck(ctrl *gomock.Controller) *MockPreCheck {
	mock := &MockPreCheck{ctrl: ctrl}
	mock.recorder = &MockPreCheckMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreCheck) EXPECT() *MockPreCheckMockRecorder {
	return m.recorder
}

// ISGOMOCK indicates that this struct is a gomock mock.
func (m *MockPreCheck) ISGOMOCK() struct{} {
	return struct{}{}
}

// PostUncheckedTxEvent mocks base method.
func (m *MockPreCheck) PostUncheckedTxEvent(ev *common.UncheckedTxEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostUncheckedTxEvent", ev)
}

// PostUncheckedTxEvent indicates an expected call of PostUncheckedTxEvent.
func (mr *MockPreCheckMockRecorder) PostUncheckedTxEvent(ev any) *MockPreCheckPostUncheckedTxEventCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostUncheckedTxEvent", reflect.TypeOf((*MockPreCheck)(nil).PostUncheckedTxEvent), ev)
	return &MockPreCheckPostUncheckedTxEventCall{Call: call}
}

// MockPreCheckPostUncheckedTxEventCall wrap *gomock.Call
type MockPreCheckPostUncheckedTxEventCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPreCheckPostUncheckedTxEventCall) Return() *MockPreCheckPostUncheckedTxEventCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPreCheckPostUncheckedTxEventCall) Do(f func(*common.UncheckedTxEvent)) *MockPreCheckPostUncheckedTxEventCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPreCheckPostUncheckedTxEventCall) DoAndReturn(f func(*common.UncheckedTxEvent)) *MockPreCheckPostUncheckedTxEventCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Start mocks base method.
func (m *MockPreCheck) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockPreCheckMockRecorder) Start() *MockPreCheckStartCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockPreCheck)(nil).Start))
	return &MockPreCheckStartCall{Call: call}
}

// MockPreCheckStartCall wrap *gomock.Call
type MockPreCheckStartCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPreCheckStartCall) Return() *MockPreCheckStartCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPreCheckStartCall) Do(f func()) *MockPreCheckStartCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPreCheckStartCall) DoAndReturn(f func()) *MockPreCheckStartCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateEpochInfo mocks base method.
func (m *MockPreCheck) UpdateEpochInfo(epoch *rbft.EpochInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateEpochInfo", epoch)
}

// UpdateEpochInfo indicates an expected call of UpdateEpochInfo.
func (mr *MockPreCheckMockRecorder) UpdateEpochInfo(epoch any) *MockPreCheckUpdateEpochInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEpochInfo", reflect.TypeOf((*MockPreCheck)(nil).UpdateEpochInfo), epoch)
	return &MockPreCheckUpdateEpochInfoCall{Call: call}
}

// MockPreCheckUpdateEpochInfoCall wrap *gomock.Call
type MockPreCheckUpdateEpochInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPreCheckUpdateEpochInfoCall) Return() *MockPreCheckUpdateEpochInfoCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPreCheckUpdateEpochInfoCall) Do(f func(*rbft.EpochInfo)) *MockPreCheckUpdateEpochInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPreCheckUpdateEpochInfoCall) DoAndReturn(f func(*rbft.EpochInfo)) *MockPreCheckUpdateEpochInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
